from random import randint

from pocketMonsters import Pokemon

from creatures1_25 import *
from creatures26_50 import *
from creatures51_75 import *
from creatures76_100 import *
from creatures101_125 import *
from creatures126_150 import *

def get_pokemon(pokemonNumber, level):
	creature = Pokemon(pokemonList[pokemonNumber], level=level)
	return creature

def random_pokemon(level):
	creature = Pokemon(pokemonList[randint(1, 150)], level=level)
	return creature

pokemonList = {}
pokemonList[1]   = Bulbasaur()
pokemonList[2]   = Ivysaur()
pokemonList[3]   = Venusaur()
pokemonList[4]   = Charmander()
pokemonList[5]   = Charmeleon()
pokemonList[6]   = Charizard()
pokemonList[7]   = Squirtle()
pokemonList[8]   = Wartortle()
pokemonList[9]   = Blastoise()
pokemonList[10]  = Caterpie()
pokemonList[11]  = Metapod()
pokemonList[12]  = Butterfree()
pokemonList[13]  = Weedle()
pokemonList[14]  = Kakuna()
pokemonList[15]  = Beedrill()
pokemonList[16]  = Pidgey()
pokemonList[17]  = Pidgeotto()
pokemonList[18]  = Pidgeot()
pokemonList[19]  = Rattata()
pokemonList[20]  = Raticate()
pokemonList[21]  = Spearow()
pokemonList[22]  = Fearow()
pokemonList[23]  = Ekans()
pokemonList[24]  = Arbok()
pokemonList[25]  = Pikachu()
pokemonList[26]  = Raichu()
pokemonList[27]  = Sandshrew()
pokemonList[28]  = Sandslash()
pokemonList[29]  = NidoranF()
pokemonList[30]  = Nidorina()
pokemonList[31]  = Nidoqueen()
pokemonList[32]  = NidoranM()
pokemonList[33]  = Nidorino()
pokemonList[34]  = Nidoking()
pokemonList[35]  = Clefairy()
pokemonList[36]  = Clefable()
pokemonList[37]  = Vulpix()
pokemonList[38]  = Ninetales()
pokemonList[39]  = Jigglypuff()
pokemonList[40]  = Wigglytuff()
pokemonList[41]  = Zubat()
pokemonList[42]  = Golbat()
pokemonList[43]  = Oddish()
pokemonList[44]  = Gloom()
pokemonList[45]  = Vileplume()
pokemonList[46]  = Paras()
pokemonList[47]  = Parasect()
pokemonList[48]  = Venonat()
pokemonList[49]  = Venomoth()
pokemonList[50]  = Diglett()
pokemonList[51]  = Dugtrio()
pokemonList[52]  = Meowth()
pokemonList[53]  = Persian()
pokemonList[54]  = Psyduck()
pokemonList[55]  = Golduck()
pokemonList[56]  = Mankey()
pokemonList[57]  = Primeape()
pokemonList[58]  = Growlithe()
pokemonList[59]  = Arcanine()
pokemonList[60]  = Poliwag()
pokemonList[61]  = Poliwhirl()
pokemonList[62]  = Poliwrath()
pokemonList[63]  = Abra()
pokemonList[64]  = Kadabra()
pokemonList[65]  = Alakazam()
pokemonList[66]  = Machop()
pokemonList[67]  = Machoke()
pokemonList[68]  = Machamp()
pokemonList[69]  = Bellsprout()
pokemonList[70]  = Weepinbell()
pokemonList[71]  = Victreebel()
pokemonList[72]  = Tentacool()
pokemonList[73]  = Tentacruel()
pokemonList[74]  = Geodude()
pokemonList[75]  = Graveler()
pokemonList[76]  = Golem()
pokemonList[77]  = Ponyta()
pokemonList[78]  = Rapidash()
pokemonList[79]  = Slowpoke()
pokemonList[80]  = Slowbro()
pokemonList[81]  = Magnemite()
pokemonList[82]  = Magneton()
pokemonList[83]  = Farfetchd()
pokemonList[84]  = Doduo()
pokemonList[85]  = Dodrio()
pokemonList[86]  = Seel()
pokemonList[87]  = Dewgong()
pokemonList[88]  = Grimer()
pokemonList[89]  = Muk()
pokemonList[90]  = Shellder()
pokemonList[91]  = Cloyster()
pokemonList[92]  = Gastly()
pokemonList[93]  = Haunter()
pokemonList[94]  = Gengar()
pokemonList[95]  = Onix()
pokemonList[96]  = Drowzee()
pokemonList[97]  = Hypno()
pokemonList[98]  = Krabby()
pokemonList[99]  = Kingler()
pokemonList[100] = Voltorb()
pokemonList[101] = Electrode()
pokemonList[102] = Exeggcute()
pokemonList[103] = Exeggutor()
pokemonList[104] = Cubone()
pokemonList[105] = Marowak()
pokemonList[106] = Hitmonlee()
pokemonList[107] = Hitmonchan()
pokemonList[108] = Lickitung()
pokemonList[109] = Koffing()
pokemonList[110] = Weezing()
pokemonList[111] = Rhyhorn()
pokemonList[112] = Rhydon()
pokemonList[113] = Chansey()
pokemonList[114] = Tangela()
pokemonList[115] = Kangaskhan()
pokemonList[116] = Horsea()
pokemonList[117] = Seadra()
pokemonList[118] = Goldeen()
pokemonList[119] = Seaking()
pokemonList[120] = Staryu()
pokemonList[121] = Starmie()
pokemonList[122] = MrMime()
pokemonList[123] = Scyther()
pokemonList[124] = Jynx()
pokemonList[125] = Electabuzz()
pokemonList[126] = Magmar()
pokemonList[127] = Pinsir()
pokemonList[128] = Tauros()
pokemonList[129] = Magikarp()
pokemonList[130] = Gyarados()
pokemonList[131] = Lapras()
pokemonList[132] = Ditto()
pokemonList[133] = Eevee()
pokemonList[134] = Vaporeon()
pokemonList[135] = Jolteon()
pokemonList[136] = Flareon()
pokemonList[137] = Porygon()
pokemonList[138] = Omanyte()
pokemonList[139] = Omastar()
pokemonList[140] = Kabuto()
pokemonList[141] = Kabutops()
pokemonList[142] = Aerodactyl()
pokemonList[143] = Snorlax()
pokemonList[144] = Articuno()
pokemonList[145] = Zapdos()
pokemonList[146] = Moltres()
pokemonList[147] = Dratini()
pokemonList[148] = Dragonair()
pokemonList[149] = Dragonite()
pokemonList[150] = Mewtwo()